### ISSUE TITLE
privacy provider class incorrect

### ISSUE THREAD

**Issue by danmarsden** [MMBR-IO/moodle-enrol_mmbr_io#20]
It looks like you might be passing the user id/email to the external service and you have not stated this in your privacy provider class. You should review all user information that you are currently sending to the external service and make sure this is explicitly defined in the privacy API.
https://docs.moodle.org/dev/Privacy_API#Indicating_that_you_export_data_to_an_external_location

here's an example of a plugin that doesn't store any user data but does send data to an external location:
https://github.com/catalyst/moodle-tool_coursebank/blob/master/classes/privacy/provider.php
That plugin only sends the userid - but I think your plugin sends other fields so you will need to make sure you include all fields you send to the external service.

**Comment by BarmaleyHD** [comment]
Hi @danmarsden. Thank you very much for your comments. Is it required for such API to provide request for data deletion?

**Comment by danmarsden** [comment]
no - it just needs to state the information so that the Moodle privacy officer can see that data is stored externally. - the facility for requesting external data deletion is not part of the API at this stage.

**Comment by BarmaleyHD** [comment]
That's great. Thanks
